install:
  - echo "Installed Python versions:"
  - dir c:\Python*

  - C:\Python35\python -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - 'set TESTENVS=
          py26,
          py27,
          py33,
          py34
    '
  - C:\Python35\python -m tox -e "%TESTENVS%"
